packages:
  - codex-cli
  - codex-electron
  - codex-rs/responses-api-proxy/npm
  - sdk/typescript
  - shell-tool-mcp

blockExoticSubdeps: true

ignoredBuiltDependencies:
  - esbuild

minimumReleaseAge: 10080

onlyBuiltDependencies:
  - electron
